#logging:
#  level:
#    org:
#      springframework:
#        boot:
#          autoconfigure:
#            logging:
#              ConditionEvaluationReportLoggingListener: debug # 等同于使用 --debug启动程序

server:
  port: 8881
logging:
  level:
    root: debug
